### ISSUE TITLE
Sometimes the screenshot files are empty

### ISSUE THREAD

**Issue by CompSciLauren** [CompSciLauren/stardew-valley-daily-screenshot-mod#26]
**Description of Bug**
Bug was reported by a player on the NexusMods website, titled "Sometimes the screenshot files are empty": https://www.nexusmods.com/stardewvalley/mods/4779?tab=bugs

**Expected behavior**
Screenshots should always display the correct image and not sometimes be an empty file.

**Comment by kins-dev** [comment]
May be related to#30 if the move is happening after the OS creates the file but before the game locks the file for writing.

**Comment by CompSciLauren** [comment]
Good to know. Since that issue is fixed now, I'll contact the player who reported the bug after I've published the next update and ask them to see if they are still experiencing the problem.

**Comment by CompSciLauren** [comment]
Closing since this was likely fixed in #32. User who originally reported the issue never responded to say if updating solved the issue or not, but no one else has reported the bug since then.
