### ISSUE TITLE
Screenshot Not Moved on Ubuntu 18.04.03 LTS

### ISSUE THREAD

**Issue by kins-dev** [CompSciLauren/stardew-valley-daily-screenshot-mod#30]
Getting the following exception:
`[Daily Screenshot] Error moving file '01-02-06.png' into Foo-Farm-Screenshots-237055866 folder. Technical details:
System.IO.IOException: Sharing violation on path /home/foo/.local/share/StardewValley/Screenshots/01-02-06.png
  at System.IO.File.Move (System.String sourceFileName, System.String destFileName) <0x42ae8bf0 + 0x002d3> in <filename unknown>:0 
  at DailyScreenshot.ModEntry.MoveScreenshotToCorrectFolder (System.String screenshotName) <0x42ae8950 + 0x001f7> in <filename unknown>:0 `

It appears the game is holding a shared lock when the mod attempts to move the file.  Possible workarounds:
- Copy then delete
- Check the file state before moving, wait if needed
- Catch the exception and retry

This was with:
- SDV 1.4.3
- SMAPI 3.1.0
- Daily Screenshot 1.1.0

Also had SDV Expanded installed if that makes a difference.

**Comment by CompSciLauren** [comment]
Resolved by #32, closing.
