### ISSUE TITLE
Support for SMAPI 3.8+

### ISSUE THREAD

**Issue by WuZhuoran** [CompSciLauren/stardew-valley-daily-screenshot-mod#39]
**Description of Bug**

With update with [SMAPI 3.8](https://smapi.io/), Daily Screenshot will be skipped because it is no longer compatible.

Traceback as below:
```
[SMAPI]    Skipped mods
[SMAPI]    --------------------------------------------------
[SMAPI]       These mods could not be added to your game.

[SMAPI]       - Daily Screenshot 2.0.0 because it's no longer compatible. Please check for a new version at https://smapi.io/mods
```

**Steps to Reproduce**
1. Download Latest SMAPI
2. Launch the game
3. Warning occured.

**Expected behavior**
No error founded.

**Comment by m4ny** [comment]
This is due to a changed signature:

`Game1.game1.takeMapScreenshot(float in_scale, string screenshot_name)` 

changed to

 `Game1.game1.takeMapScreenshot(float in_scale, string screenshot_name, Action onDone)`

An empty lambda would make the mod functional again.

For example (`ModEntry.cs:531`):

```
string mapScreenshotPath = Game1.game1.takeMapScreenshot(rule.ZoomLevel, ssPath, () => {
		//Nothing here. Just added Action as empty lambda to provide all now required parameters.
	}
);
```
