### ISSUE TITLE
Option to disable snapshot visual effect

### ISSUE THREAD

**Issue by CompSciLauren** [CompSciLauren/stardew-valley-daily-screenshot-mod#42]
**Is your feature request related to a problem? Please describe.**
From a user's comment on the Nexus website: "could you make the 'snapshot' effect and sound be configurable?
Me being slightly photophobic, I try to disable most 'flashbang'-like effects in games."

**Describe the solution you'd like**
See if the snapshot effect described can be disabled. If so, then have it enabled by default. But allow the user to disable it in the config.

**Describe alternatives you've considered**
If the snapshot effect cannot be disabled, then I don't know what else could be done about it. Needs investigating to find out if this is possible or not, and if there could be any alternative ideas.

**Comment by jltaylor-us** [comment]
Isn't this just a matter of conditionalizing the `Game1.flashAlpha1` (ModEntry.cs:522) and `Game1.playSound` (ModEntry.cs:536)?

It also looks to me like unchecking the "Show Flash Effects" game option will suppress the flash effect, but I haven't installed the mod to try it out.  (I posted this suggestion in the thread on nexusmods, so perhaps the user will try it out.)

**Comment by CompSciLauren** [comment]
This is now completed and has been added as part of the 3.0 release! Closing.
